# Generated by Django 6.0 on 2026-02-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('mobile', 'Mobile Phone'), ('headset', 'Headset'), ('waterbottle', 'Water Bottle'), ('idcard', 'ID Card'), ('books', 'Books'), ('laptop', 'Laptop'), ('charger', 'Charger'), ('wallet', 'Wallet'), ('keys', 'Keys'), ('bag', 'Bag'), ('jewelry', 'Jewelry'), ('clothing', 'Clothing'), ('other', 'Other')], max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('new', 'Like New'), ('good', 'Good'), ('worn', 'Worn'), ('damaged', 'Damaged')], max_length=20)),
                ('description', models.TextField()),
                ('found_location', models.CharField(max_length=255)),
                ('found_date', models.DateTimeField()),
                ('storage_location', models.CharField(choices=[('with-me', 'With Finder'), ('security-desk', 'Security Desk'), ('lost-found-office', 'Lost & Found Office'), ('reception', 'Reception'), ('police-station', 'Police Station'), ('other-location', 'Other')], max_length=50)),
                ('specific_storage_location', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(upload_to='found_items/')),
                ('finder_name', models.CharField(max_length=100)),
                ('finder_email', models.EmailField(max_length=254)),
                ('finder_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('mobile', 'Mobile Phone'), ('headset', 'Headset'), ('waterbottle', 'Water Bottle'), ('idcard', 'ID Card'), ('books', 'Books'), ('laptop', 'Laptop'), ('charger', 'Charger'), ('wallet', 'Wallet'), ('keys', 'Keys'), ('bag', 'Bag'), ('jewelry', 'Jewelry'), ('clothing', 'Clothing'), ('other', 'Other')], max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('lost_location', models.CharField(max_length=255)),
                ('lost_date', models.DateTimeField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
