# Generated by Django 6.0 on 2026-02-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='color',
        ),
    ]
